{
 "title": "Selectronic Current State",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Battery State-of-Charge",
   "type": "stat",
   "description": "House battery state-of-charge in percent",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "selectronic",
     "select": [
      [
       { "params": [ "battery_soc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "selectronic",
     "select": [
      [
       { "params": [ "load_w" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery power flow",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "selectronic",
     "query": "SELECT last(\"battery_w\")  * -1.0 FROM \"selectronic\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "battery_w" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Production",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "selectronic",
     "select": [
      [
       { "params": [ "solarinverter_w" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Generator production",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "selectronic",
     "query": "SELECT last(\"grid_w\") * -1.0 FROM \"selectronic\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "grid_w" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}